name: Update Branch Name

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'scripts/update_radio.sh'
  create:
    branches:
      - '*'

jobs:
  update-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          
      - name: Update branch name in update_radio.sh
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"
          sed -i "s/BRANCH=\".*\"/BRANCH=\"$CURRENT_BRANCH\"/" scripts/update_radio.sh
          
      - name: Check if file changed
        id: changes
        run: |
          if [[ -n "$(git status --porcelain scripts/update_radio.sh)" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update branch name in update_radio.sh [skip ci]
          title: 'Update branch name in update_radio.sh'
          body: 'Automated update of branch name in update_radio.sh'
          branch: update-branch-name
          base: ${{ github.ref }}
